### ISSUE TITLE
can this tool be made recursive ?

### ISSUE THREAD

**Issue by J0SH1X** [joshuous/aosp-missing-blobs#1]
its very hard to get all folders to be detected , maybe can this tool be made recursive so you can just set vendor and system as paths and the tool will recursivly scan folders

**Comment by joshuous** [comment]
Hi is your intention to use it like this?

`$ java -jar MissingBlobs.jar ~/system ~/vendor`

**Comment by saurabhchardereal** [comment]
I was going to add an issue requesting the same but found it was already requested ... an year ago.

@joshuous since the OP hasn't replied, I'd like to chime in just to request that the recursive feature is really needed to get around listing every `lib(64)` directories to the program which is cumbersome sometimes (to me atleast). It would be nice to have a recursive option.

**Comment by joshuous** [comment]
Can you provide an example of the preferred syntax for traversing blobs recursively? Would you expect it to respect the .gitignore file?

**Comment by saurabhchardereal** [comment]
The preferred way to do recursive globbing is to have an option for it specifically, so that the users have both options (i.e, you can parse through blobs recursively or individually)  like how `grep` works with `grep -r`.

Something like:
``` shell
./aosp-missing-blobs -r ~/system ~/vendor
```

Also, it may be subjective but I do not expect it to respect `.gitignore` whatsoever as most of the time I'll be running it either inside `out` directory of AOSP's build system (when I just finished cooking a fresh custom ROM) or inside a stripped out stock ROM dump - in both cases, `.gitignore` isn't present.

**Comment by joshuous** [comment]
@saurabhchardereal, can you give this branch a try and let me know how it works for you? Use the `-r` flag to make it recursive.

https://github.com/joshuous/aosp-missing-blobs/tree/clap-cli

Warning that you should avoid comparing lib and lib64 blobs because they are different

**Comment by saurabhchardereal** [comment]
This seems to be working as expected. Also asked my friend to confirm if it works for him too. Working properly for both of us.

Thanks!
